"""Generate a small GUI usability checklist for the card factory panel."""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


REPORTS = Path("reports")
OUTPUT = Path("output")

CHECKS = [
    ("Start", "Can the user tell what this window is for?"),
    ("Input", "Are labels close to the fields they describe?"),
    ("Action", "Is the main button easy to find and click?"),
    ("Feedback", "Does the window confirm when the card is saved?"),
    ("Recovery", "Can the user fix an empty title or missing note?"),
]


def font(size: int, bold: bool = False):
    candidates = [
        "C:/Windows/Fonts/msyhbd.ttc" if bold else "C:/Windows/Fonts/msyh.ttc",
        "C:/Windows/Fonts/simhei.ttf",
        "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def write_markdown():
    REPORTS.mkdir(exist_ok=True)
    lines = [
        "# 第4章 GUI 可用性检查清单",
        "",
        "这份清单由 Python 生成，用来检查 Tkinter 小窗口是否真的方便使用。",
        "",
        "| 环节 | 检查问题 |",
        "| --- | --- |",
    ]
    for stage, question in CHECKS:
        lines.append(f"| {stage} | {question} |")
    lines.extend(
        [
            "",
            "复盘提示：GUI 的目标不是把按钮摆满，而是让用户少猜、少错、少迷路。",
        ]
    )
    path = REPORTS / "ch04_gui_usability_check.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_preview():
    OUTPUT.mkdir(exist_ok=True)
    im = Image.new("RGB", (1500, 980), "#F7F8FB")
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((90, 70, 1410, 900), radius=26, fill="#FFFFFF", outline="#D8E0EC", width=3)
    d.text((150, 125), "GUI Usability Check", fill="#162033", font=font(52, True))
    d.text((152, 200), "A tiny checklist generated by Python.", fill="#5F6673", font=font(28))

    colors = ["#2F6BFF", "#24A06B", "#F28C28", "#7A5AF8", "#18A9B5"]
    for i, (stage, question) in enumerate(CHECKS):
        y = 300 + i * 105
        color = colors[i % len(colors)]
        d.rounded_rectangle((150, y, 360, y + 66), radius=18, fill=color)
        d.text((182, y + 17), stage, fill="#FFFFFF", font=font(26, True))
        d.rounded_rectangle((390, y, 1295, y + 66), radius=18, fill="#F1F5F9", outline="#E2E8F0", width=2)
        d.text((420, y + 18), question, fill="#162033", font=font(23))

    path = OUTPUT / "ch04_gui_usability_check.png"
    im.save(path, optimize=True)
    return path


def main():
    md = write_markdown()
    preview = write_preview()
    print("已生成 GUI 可用性检查清单：")
    print(f"- {md}")
    print(f"- {preview}")


if __name__ == "__main__":
    main()
