"""Create a visual evidence archive for chapter 09 outputs."""

from __future__ import annotations

import shutil
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "output"
REPORTS = ROOT / "reports"
WEB_DIR = ROOT / "assets" / "ch09" / "web"

PREVIEW = OUTPUT / "visual_evidence_archive.png"
REPORT = REPORTS / "ch09_visual_evidence_archive.md"
ASSET_COPY = WEB_DIR / "visual_evidence_archive.png"

SOURCES = [
    ("原始卡片", OUTPUT / "demo_card_image.png"),
    ("灰度版本", OUTPUT / "demo_card_image_gray.png"),
    ("真实照片处理", OUTPUT / "fronalpstock_before_after.png"),
    ("知觉实验台", OUTPUT / "ch09_visual_perception_lab.png"),
    ("质量总览", OUTPUT / "ch09_image_quality_contact_sheet.png"),
    ("处理故事板", OUTPUT / "ch09_processing_storyboard.png"),
    ("ch8 素材入库", OUTPUT / "ch09_ch08_image_intake.png"),
]


def font(size: int, bold: bool = False):
    candidates = [
        Path("C:/Windows/Fonts/msyhbd.ttc") if bold else Path("C:/Windows/Fonts/msyh.ttc"),
        Path("C:/Windows/Fonts/simhei.ttf"),
        Path("C:/Windows/Fonts/segoeuib.ttf") if bold else Path("C:/Windows/Fonts/segoeui.ttf"),
        Path("C:/Windows/Fonts/arialbd.ttf") if bold else Path("C:/Windows/Fonts/arial.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size=size)
    return ImageFont.load_default()


def image_info(path: Path) -> dict[str, str | int]:
    if not path.exists():
        return {"file": path.as_posix(), "status": "missing", "width": 0, "height": 0}
    with Image.open(path) as im:
        im = ImageOps.exif_transpose(im)
        width, height = im.size
    return {"file": path.as_posix(), "status": "ready", "width": width, "height": height}


def fit_thumb(path: Path, size: tuple[int, int]) -> Image.Image:
    if not path.exists():
        thumb = Image.new("RGB", size, "#FEE2E2")
        d = ImageDraw.Draw(thumb)
        d.line((70, 55, size[0] - 70, size[1] - 55), fill="#E84C61", width=8)
        d.line((size[0] - 70, 55, 70, size[1] - 55), fill="#E84C61", width=8)
        return thumb

    with Image.open(path) as raw:
        raw = ImageOps.exif_transpose(raw).convert("RGB")
        return ImageOps.contain(raw, size, method=getattr(Image, "Resampling", Image).LANCZOS)


def draw_archive() -> list[dict[str, str | int]]:
    OUTPUT.mkdir(exist_ok=True)
    rows = []
    image = Image.new("RGB", (1700, 1220), "#F7F8FB")
    draw = ImageDraw.Draw(image)

    title_font = font(54, True)
    subtitle_font = font(24)
    label_font = font(23, True)
    small_font = font(18)

    draw.rounded_rectangle((80, 70, 1620, 1145), radius=30, fill="#FFFFFF", outline="#D8E0EC", width=3)
    draw.text((140, 120), "Visual Evidence Archive", fill="#162033", font=title_font)
    draw.text((142, 190), "Chapter 09 outputs gathered as reproducible image evidence.", fill="#64748B", font=subtitle_font)

    positions = [(130, 275), (510, 275), (890, 275), (1270, 275), (130, 640), (510, 640), (890, 640)]
    for (label, path), (x, y) in zip(SOURCES, positions):
        info = image_info(path)
        rows.append({"label": label, **info})
        draw.rounded_rectangle((x, y, x + 330, y + 285), radius=24, fill="#F8FAFC", outline="#E2E8F0", width=2)
        draw.rounded_rectangle((x + 22, y + 24, x + 308, y + 195), radius=18, fill="#FFFFFF", outline="#D8E0EC", width=1)
        thumb = fit_thumb(path, (266, 151))
        image.paste(thumb, (x + 32 + (266 - thumb.width) // 2, y + 34 + (151 - thumb.height) // 2))

        status = str(info["status"])
        status_color = "#24A06B" if status == "ready" else "#E84C61"
        draw.text((x + 24, y + 210), label, fill="#162033", font=label_font)
        draw.ellipse((x + 24, y + 250, x + 44, y + 270), fill=status_color)
        draw.text((x + 56, y + 244), status, fill=status_color, font=small_font)
        size_text = f"{info['width']} x {info['height']}"
        draw.text((x + 168, y + 244), size_text, fill="#64748B", font=small_font)

    draw.rounded_rectangle((260, 1090, 1440, 1130), radius=18, fill="#EFF6FF", outline="#BFDBFE", width=2)
    draw.text((480, 1098), "Generated by code/ch09/09_make_visual_evidence_archive.py", fill="#1D4ED8", font=small_font)

    image.save(PREVIEW, optimize=True, quality=95)
    WEB_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(PREVIEW, ASSET_COPY)
    return rows


def write_report(rows: list[dict[str, str | int]]) -> None:
    REPORTS.mkdir(exist_ok=True)
    lines = [
        "# 第9章视觉证据档案",
        "",
        "这份档案由 Python 自动生成，用来把本章的关键图像处理产物集中到一张可检查的总览图里。",
        "",
        "| 项目 | 文件 | 状态 | 尺寸 |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['label']} | `{row['file']}` | {row['status']} | "
            f"{row['width']}x{row['height']} |"
        )
    lines.extend(
        [
            "",
            "## 复盘提醒",
            "",
            "- 图像处理不是只追求“好看”，还要保留原图、处理步骤和输出证据。",
            "- 教学配图要先服务理解，再追求风格；如果处理让关键信息变模糊，就应该回退。",
            "- 科研材料尤其要可复现：同一张原图、同一段代码、同一组参数，应该能重新生成同样的结果。",
        ]
    )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = draw_archive()
    write_report(rows)
    print(f"created {PREVIEW.relative_to(ROOT)}")
    print(f"created {REPORT.relative_to(ROOT)}")
    print(f"synced {ASSET_COPY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
