"""Create a runtime evidence overview for chapter 09 image processing."""

from __future__ import annotations

import shutil
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def project_root() -> Path:
    here = Path.cwd()
    if (here / "assets" / "ch09").exists():
        return here
    return Path(__file__).resolve().parents[2]


ROOT = project_root()
OUTPUT = ROOT / "output"
REPORTS = ROOT / "reports"
WEB_DIR = ROOT / "assets" / "ch09" / "web"

PREVIEW = OUTPUT / "ch09_image_runtime_evidence.png"
REPORT = REPORTS / "ch09_image_runtime_evidence.md"
ASSET_COPY = WEB_DIR / "ch09_image_runtime_evidence.png"

CHECKS = [
    ("01 demo image", OUTPUT / "demo_card_image.png"),
    ("02 grayscale", OUTPUT / "demo_card_image_gray.png"),
    ("04 real photo sheet", OUTPUT / "fronalpstock_before_after.png"),
    ("05 report md", REPORTS / "ch09_image_processing_report.md"),
    ("05 report preview", REPORTS / "ch09_image_processing_report_preview.png"),
    ("06 perception report", REPORTS / "ch09_visual_perception_lab.md"),
    ("06 perception image", OUTPUT / "ch09_visual_perception_lab.png"),
    ("07 quality report", REPORTS / "ch09_image_quality_contact_sheet.md"),
    ("07 quality sheet", OUTPUT / "ch09_image_quality_contact_sheet.png"),
    ("08 ch08 intake report", REPORTS / "ch09_ch08_image_intake.md"),
    ("08 ch08 intake json", OUTPUT / "ch09_ch08_image_intake.json"),
    ("08 ch08 intake image", OUTPUT / "ch09_ch08_image_intake.png"),
    ("10 storyboard report", REPORTS / "ch09_processing_storyboard.md"),
    ("10 storyboard image", OUTPUT / "ch09_processing_storyboard.png"),
    ("09 archive report", REPORTS / "ch09_visual_evidence_archive.md"),
    ("09 archive image", OUTPUT / "visual_evidence_archive.png"),
]


def font(size: int, bold: bool = False):
    candidates = [
        Path("C:/Windows/Fonts/segoeuib.ttf") if bold else Path("C:/Windows/Fonts/segoeui.ttf"),
        Path("C:/Windows/Fonts/arialbd.ttf") if bold else Path("C:/Windows/Fonts/arial.ttf"),
        Path("C:/Windows/Fonts/msyhbd.ttc") if bold else Path("C:/Windows/Fonts/msyh.ttc"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size=size)
    return ImageFont.load_default()


def status_rows() -> list[dict[str, str | int]]:
    rows = []
    for label, path in CHECKS:
        exists = path.exists()
        size = path.stat().st_size if exists else 0
        rows.append(
            {
                "label": label,
                "path": path.relative_to(ROOT).as_posix(),
                "status": "OK" if exists else "MISSING",
                "bytes": size,
            }
        )
    return rows


def draw_preview(rows: list[dict[str, str | int]]) -> None:
    OUTPUT.mkdir(exist_ok=True)
    image = Image.new("RGB", (1760, 1320), "#F7F8FB")
    draw = ImageDraw.Draw(image)

    title_font = font(46, True)
    mono_font = font(25)
    small_font = font(21)

    draw.rounded_rectangle((85, 70, 1675, 1245), radius=34, fill="#FFFFFF", outline="#D8E0EC", width=3)
    draw.rectangle((145, 130, 1615, 184), fill="#E7EEF7")
    draw.text((165, 143), "Windows PowerShell - ch09 image runtime evidence", fill="#1B2733", font=small_font)
    draw.rectangle((145, 184, 1615, 1140), fill="#113A6B")

    y = 220
    draw.text((170, y), "PS> cd python_tutorial_ch09", fill="#59D9FF", font=mono_font)
    y += 38
    draw.text((170, y), "PS> run image-processing scripts 01..11", fill="#59D9FF", font=mono_font)
    y += 54

    ok_count = sum(1 for row in rows if row["status"] == "OK")
    draw.text((170, y), f"Runtime artifacts: {ok_count}/{len(rows)} ready", fill="#68F06A", font=title_font)
    y += 72

    for row in rows:
        status = str(row["status"])
        color = "#68F06A" if status == "OK" else "#FFB4B4"
        bytes_count = int(row["bytes"])
        size_text = f"{bytes_count / 1024:7.1f} KB" if bytes_count else "   --   "
        line = f"[{status:<7}] {row['label']:<24} {size_text}  {row['path']}"
        if len(line) > 102:
            line = line[:99] + "..."
        draw.text((170, y), line, fill=color if status != "OK" else "#F3F8FF", font=mono_font)
        y += 43

    draw.text((170, 1165), "Generated by code/ch09/11_make_image_runtime_evidence.py", fill="#64748B", font=small_font)
    image.save(PREVIEW, optimize=True, quality=95)


def write_report(rows: list[dict[str, str | int]]) -> None:
    REPORTS.mkdir(exist_ok=True)
    ready = sum(1 for row in rows if row["status"] == "OK")
    lines = [
        "# 第9章图像处理运行证据",
        "",
        f"本报告由 `11_make_image_runtime_evidence.py` 生成，用来检查第9章关键图像处理产物是否已经落盘。当前状态：{ready}/{len(rows)} ready。",
        "",
        "| 项目 | 文件 | 状态 | 大小 |",
        "| --- | --- | --- | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['label']} | `{row['path']}` | {row['status']} | {int(row['bytes'])} |"
        )
    lines.extend(
        [
            "",
            "## 复盘提醒",
            "",
            "- 图像处理不要只留下最终图，也要留下原图、灰度图、处理报告和证据档案。",
            "- 图片进入教程、报告或课件前，至少检查尺寸、视野、清晰度和来源记录。",
            "- 如果某个项目显示 missing，先运行对应脚本，再重新运行本脚本。",
        ]
    )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def copy_asset() -> None:
    WEB_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(PREVIEW, ASSET_COPY)


def main() -> None:
    rows = status_rows()
    draw_preview(rows)
    write_report(rows)
    copy_asset()
    print("created image runtime evidence:")
    print(f"- {REPORT}")
    print(f"- {PREVIEW}")
    print(f"- {ASSET_COPY}")


if __name__ == "__main__":
    main()
