"""Create a final showcase board for the chapter 10 delivery artifacts."""

from __future__ import annotations

import shutil
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps


ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / "reports"
WEB_DIR = ROOT / "assets" / "ch10" / "web"

PREVIEW = REPORTS / "final_showcase_board.png"
REPORT = REPORTS / "final_showcase_board.md"
ASSET_COPY = WEB_DIR / "final_showcase_board.png"
DOSSIER = REPORTS / "capstone_handoff_dossier.png"
DOSSIER_REPORT = REPORTS / "capstone_handoff_dossier.md"
DOSSIER_COPY = WEB_DIR / "capstone_handoff_dossier.png"

ITEMS = [
    ("报告预览", REPORTS / "final_report_preview.png"),
    ("Excel 预览", REPORTS / "excel_workbook_preview.png"),
    ("课程作品集", REPORTS / "course_portfolio_preview.png"),
    ("交付索引", REPORTS / "delivery_index_preview.png"),
    ("Word 报告", REPORTS / "final_report.docx"),
    ("PPT 展示", REPORTS / "final_slides.pptx"),
]


def font(size: int, bold: bool = False):
    candidates = [
        Path("C:/Windows/Fonts/msyhbd.ttc") if bold else Path("C:/Windows/Fonts/msyh.ttc"),
        Path("C:/Windows/Fonts/simhei.ttf"),
        Path("C:/Windows/Fonts/segoeuib.ttf") if bold else Path("C:/Windows/Fonts/segoeui.ttf"),
        Path("C:/Windows/Fonts/arialbd.ttf") if bold else Path("C:/Windows/Fonts/arial.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size=size)
    return ImageFont.load_default()


def draw_file_icon(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], color: str, label: str) -> None:
    x1, y1, x2, y2 = box
    cx = (x1 + x2) // 2
    cy = (y1 + y2) // 2
    draw.rounded_rectangle((cx - 58, cy - 70, cx + 58, cy + 70), radius=18, fill="#FFFFFF", outline=color, width=7)
    draw.line((cx - 30, cy - 15, cx + 30, cy - 15), fill=color, width=6)
    draw.line((cx - 30, cy + 12, cx + 30, cy + 12), fill=color, width=6)
    draw.text((cx - 38, cy + 38), label, fill=color, font=font(24, True))


def thumb(path: Path, size: tuple[int, int], label: str) -> Image.Image:
    if path.suffix.lower() in {".png", ".jpg", ".jpeg"} and path.exists():
        raw = Image.open(path)
        raw = ImageOps.exif_transpose(raw).convert("RGB")
        return ImageOps.contain(raw, size, method=getattr(Image, "Resampling", Image).LANCZOS)

    image = Image.new("RGB", size, "#F8FAFC")
    draw = ImageDraw.Draw(image)
    color = "#2F6BFF" if path.suffix.lower() in {".docx", ".md"} else "#F28C28"
    draw_file_icon(draw, (0, 0, size[0], size[1]), color, label)
    return image


def file_status(path: Path) -> tuple[str, int]:
    if path.exists():
        return "ready", path.stat().st_size
    return "missing", 0


def draw_showcase() -> list[dict[str, str | int]]:
    REPORTS.mkdir(exist_ok=True)
    rows: list[dict[str, str | int]] = []
    image = Image.new("RGB", (1700, 1180), "#F7F8FB")
    draw = ImageDraw.Draw(image)

    draw.rounded_rectangle((80, 70, 1620, 1090), radius=30, fill="#FFFFFF", outline="#D8E0EC", width=3)
    draw.text((140, 120), "Final Showcase Board", fill="#162033", font=font(54, True))
    draw.text((142, 190), "Chapter 10 artifacts arranged for a teaching share.", fill="#64748B", font=font(24))

    positions = [(140, 275), (620, 275), (1100, 275), (140, 680), (620, 680), (1100, 680)]
    colors = ["#2F6BFF", "#24A06B", "#7A5AF8", "#F28C28", "#18A9B5", "#E84C61"]
    for (item, (x, y), color) in zip(ITEMS, positions, colors):
        label, path = item
        status, size = file_status(path)
        rows.append({"label": label, "file": path.as_posix(), "status": status, "size": size})

        draw.rounded_rectangle((x, y, x + 420, y + 330), radius=24, fill="#F8FAFC", outline="#E2E8F0", width=2)
        draw.rounded_rectangle((x + 24, y + 25, x + 396, y + 230), radius=18, fill="#FFFFFF", outline="#D8E0EC", width=1)
        shown = thumb(path, (352, 185), path.suffix.upper().replace(".", "")[:4])
        image.paste(shown, (x + 34 + (352 - shown.width) // 2, y + 35 + (185 - shown.height) // 2))
        draw.text((x + 28, y + 253), label, fill="#162033", font=font(24, True))
        status_color = "#24A06B" if status == "ready" else "#E84C61"
        draw.ellipse((x + 28, y + 292, x + 50, y + 314), fill=status_color)
        draw.text((x + 62, y + 286), status, fill=status_color, font=font(19, True))
        draw.text((x + 178, y + 286), f"{size} bytes", fill="#64748B", font=font(19))
        draw.rounded_rectangle((x + 292, y + 285, x + 392, y + 314), radius=15, fill=color)
        draw.text((x + 318, y + 289), "show", fill="#FFFFFF", font=font(16, True))

    draw.rounded_rectangle((245, 1030, 1455, 1070), radius=18, fill="#EFF6FF", outline="#BFDBFE", width=2)
    draw.text((470, 1038), "Generated by code/ch10/09_make_final_showcase_board.py", fill="#1D4ED8", font=font(18))
    image.save(PREVIEW, optimize=True, quality=95)
    WEB_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(PREVIEW, ASSET_COPY)
    return rows


def write_report(rows: list[dict[str, str | int]]) -> None:
    lines = [
        "# 第10章结课展示墙",
        "",
        "这份展示墙由 Python 自动生成，用来把第10章的关键交付物摆成一张可检查、可展示的总览图。",
        "",
        "| 展示项 | 文件 | 状态 | 大小 bytes |",
        "| --- | --- | --- | ---: |",
    ]
    for row in rows:
        lines.append(f"| {row['label']} | `{row['file']}` | {row['status']} | {row['size']} |")
    lines.extend(
        [
            "",
            "## 分享提醒",
            "",
            "- 结课展示时先展示作品集，再展示报告、表格、PPT 和交付回执。",
            "- 如果某个文件状态不是 ready，先回到对应脚本重新生成，再打包交付。",
            "- 展示墙不是替代原文件，而是帮助观众一眼看到自动化流程的成果。",
        ]
    )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def draw_capstone_dossier(rows: list[dict[str, str | int]]) -> None:
    ready = sum(1 for row in rows if row["status"] == "ready")
    image = Image.new("RGB", (1700, 1120), "#F6F8FB")
    draw = ImageDraw.Draw(image)

    ink = "#162033"
    muted = "#64748B"
    blue = "#2F6BFF"
    green = "#24A06B"
    orange = "#F28C28"
    purple = "#7A5AF8"
    red = "#E84C61"
    line = "#D8E0EC"

    draw.rounded_rectangle((95, 72, 1605, 1035), radius=34, fill="#FFFFFF", outline=line, width=3)
    draw.text((155, 122), "Capstone Handoff Dossier", fill=ink, font=font(54, True))
    draw.text((158, 194), "The course ends as a visible package, not a pile of forgotten files.", fill=muted, font=font(25))

    # Left: a desk-like handoff folder. It is mostly visual; details live in Markdown.
    draw.rounded_rectangle((150, 285, 735, 880), radius=30, fill="#F8FAFC", outline="#D8E0EC", width=2)
    draw.rounded_rectangle((220, 390, 660, 725), radius=24, fill="#FFF7E8", outline="#E7BE65", width=5)
    draw.polygon([(220, 390), (360, 390), (405, 455), (660, 455), (660, 390)], fill="#FBE4AE")
    draw.rounded_rectangle((255, 485, 625, 665), radius=18, fill="#FFFFFF", outline="#E2E8F0", width=2)
    for i, color in enumerate([blue, green, orange, purple, red]):
        y = 520 + i * 27
        draw.rounded_rectangle((295, y, 585, y + 12), radius=6, fill="#E7EEF8")
        draw.rounded_rectangle((295, y, 390 + i * 42, y + 12), radius=6, fill=color)
    draw.ellipse((475, 660, 615, 800), outline=green, width=12)
    draw.line((575, 760, 650, 835), fill=green, width=16)
    draw.text((260, 765), f"{ready}/{len(rows)}", fill=green, font=font(42, True))
    draw.text((260, 820), "ready", fill=muted, font=font(22))

    # Right: eleven chapters become a single portfolio arc.
    draw.rounded_rectangle((795, 285, 1545, 880), radius=30, fill="#F8FAFC", outline="#D8E0EC", width=2)
    draw.text((850, 332), "Course Arc", fill=ink, font=font(32, True))
    draw.text((852, 377), "ch00 to ch10", fill=muted, font=font(22))
    arc_colors = [blue, green, orange, purple, "#18A9B5", red]
    points = []
    for i in range(11):
        x = 875 + i * 60
        y = 690 - int(170 * (i / 10)) + (25 if i % 2 else -15)
        points.append((x, y))
    draw.line(points, fill="#C8D4E5", width=7)
    for i, (x, y) in enumerate(points):
        color = arc_colors[i % len(arc_colors)]
        draw.ellipse((x - 20, y - 20, x + 20, y + 20), fill="#FFFFFF", outline=color, width=6)
        draw.text((x - 15, y + 30), f"{i}", fill=color, font=font(17, True))
    draw.rounded_rectangle((850, 760, 1488, 820), radius=22, fill="#ECFDF5", outline="#A7F3D0", width=2)
    draw.text((915, 776), "portfolio + report + slides + package", fill="#047857", font=font(22, True))

    draw.rounded_rectangle((180, 930, 1520, 990), radius=22, fill="#EFF6FF", outline="#BFDBFE", width=2)
    draw.text((470, 947), "Generated by code/ch10/09_make_final_showcase_board.py", fill="#1D4ED8", font=font(21))

    image.save(DOSSIER, optimize=True, quality=95)
    WEB_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(DOSSIER, DOSSIER_COPY)


def write_dossier_report(rows: list[dict[str, str | int]]) -> None:
    ready = sum(1 for row in rows if row["status"] == "ready")
    lines = [
        "# 第10章结课交付档案",
        "",
        "这份交付档案由 `09_make_final_showcase_board.py` 生成，用来把结课作品从“文件列表”提升为“可讲述的成果包”。",
        "",
        f"- 展示项 ready：{ready}/{len(rows)}",
        "- 档案图：`reports/capstone_handoff_dossier.png`",
        "- 正式配图来源：`assets/ch10/web/capstone_handoff_dossier.png`",
        "",
        "它适合放在结课展示的最后：前面展示具体文件，最后用这一张图收束整门课的路线，让学生看到自己不是零散学了几个 API，而是完成了一套能整理、生成、检查、展示和交付的自动化流程。",
        "",
    ]
    DOSSIER_REPORT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = draw_showcase()
    write_report(rows)
    draw_capstone_dossier(rows)
    write_dossier_report(rows)
    print(f"已生成 {PREVIEW.relative_to(ROOT)}")
    print(f"已生成 {REPORT.relative_to(ROOT)}")
    print(f"已复制 {ASSET_COPY.relative_to(ROOT)}")
    print(f"已生成 {DOSSIER.relative_to(ROOT)}")
    print(f"已生成 {DOSSIER_REPORT.relative_to(ROOT)}")
    print(f"已复制 {DOSSIER_COPY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
